name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet first-time issuers
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hello there! Welcome to our repository! 🎉 As a first-time issuer, we're excited to have you here. If you have any questions or need assistance, feel free to ask! Enjoy your time contributing to our gooey world! 🟢"

      - name: Greet first-time pull requesters
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "👋 Greetings, first-time pull requester! 🌟 We're thrilled to see your contribution! Remember, our gooey community is here to support you. Keep up the good work and continue spreading the gooey vibes! 🟢"
